import 'package:fitflow/features/workout/workout_models.dart';
import 'package:flutter/material.dart';

abstract final class WorkoutCatalog {
  static const fullBodyStrength = Workout(
    id: 'full-body-strength',
    name: 'Full Body Strength',
    category: WorkoutCategory.fullBody,
    durationMinutes: 45,
    calories: 420,
    difficulty: WorkoutDifficulty.intermediate,
    exercises: [
      Exercise(
        id: 'jumping-jacks',
        name: 'Jumping Jacks',
        sets: 3,
        repetitions: 20,
        restSeconds: 30,
        icon: Icons.directions_run,
      ),
      Exercise(
        id: 'goblet-squats',
        name: 'Goblet Squats',
        sets: 4,
        repetitions: 12,
        restSeconds: 60,
        icon: Icons.accessibility_new,
      ),
      Exercise(
        id: 'push-ups',
        name: 'Push-Ups',
        sets: 3,
        repetitions: 12,
        restSeconds: 45,
        icon: Icons.fitness_center,
      ),
      Exercise(
        id: 'dumbbell-rows',
        name: 'Dumbbell Rows',
        sets: 4,
        repetitions: 10,
        restSeconds: 60,
        icon: Icons.swap_vert,
      ),
      Exercise(
        id: 'walking-lunges',
        name: 'Walking Lunges',
        sets: 3,
        repetitions: 12,
        restSeconds: 45,
        icon: Icons.directions_walk,
      ),
      Exercise(
        id: 'shoulder-press',
        name: 'Shoulder Press',
        sets: 3,
        repetitions: 10,
        restSeconds: 60,
        icon: Icons.arrow_upward,
      ),
      Exercise(
        id: 'glute-bridges',
        name: 'Glute Bridges',
        sets: 3,
        repetitions: 15,
        restSeconds: 30,
        icon: Icons.airline_seat_recline_normal,
      ),
      Exercise(
        id: 'bicycle-crunches',
        name: 'Bicycle Crunches',
        sets: 3,
        repetitions: 16,
        restSeconds: 30,
        icon: Icons.autorenew,
      ),
    ],
  );

  static const List<Workout> workouts = [
    Workout(
      id: 'upper-body-power',
      name: 'Upper Body Power',
      category: WorkoutCategory.strength,
      durationMinutes: 35,
      calories: 310,
      difficulty: WorkoutDifficulty.intermediate,
      exercises: [
        Exercise(
          id: 'bench-press',
          name: 'Bench Press',
          sets: 4,
          repetitions: 8,
          restSeconds: 90,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'bent-over-row',
          name: 'Bent-Over Row',
          sets: 4,
          repetitions: 8,
          restSeconds: 90,
          icon: Icons.swap_vert,
        ),
        Exercise(
          id: 'overhead-press',
          name: 'Overhead Press',
          sets: 3,
          repetitions: 10,
          restSeconds: 60,
          icon: Icons.arrow_upward,
        ),
        Exercise(
          id: 'pull-ups',
          name: 'Pull-Ups',
          sets: 3,
          repetitions: 6,
          restSeconds: 90,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'biceps-curl',
          name: 'Biceps Curl',
          sets: 3,
          repetitions: 12,
          restSeconds: 45,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'triceps-dip',
          name: 'Triceps Dip',
          sets: 3,
          repetitions: 10,
          restSeconds: 45,
          icon: Icons.south,
        ),
      ],
    ),
    Workout(
      id: 'lower-body-builder',
      name: 'Lower Body Builder',
      category: WorkoutCategory.strength,
      durationMinutes: 40,
      calories: 380,
      difficulty: WorkoutDifficulty.advanced,
      exercises: [
        Exercise(
          id: 'back-squat',
          name: 'Back Squat',
          sets: 4,
          repetitions: 8,
          restSeconds: 90,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'romanian-deadlift',
          name: 'Romanian Deadlift',
          sets: 4,
          repetitions: 8,
          restSeconds: 90,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'walking-lunge',
          name: 'Walking Lunge',
          sets: 3,
          repetitions: 12,
          restSeconds: 60,
          icon: Icons.directions_walk,
        ),
        Exercise(
          id: 'leg-press',
          name: 'Leg Press',
          sets: 3,
          repetitions: 10,
          restSeconds: 75,
          icon: Icons.airline_seat_recline_extra,
        ),
        Exercise(
          id: 'calf-raise',
          name: 'Calf Raise',
          sets: 3,
          repetitions: 15,
          restSeconds: 45,
          icon: Icons.arrow_upward,
        ),
        Exercise(
          id: 'wall-sit',
          name: 'Wall Sit',
          sets: 3,
          repetitions: 12,
          restSeconds: 45,
          icon: Icons.crop_square,
        ),
      ],
    ),
    Workout(
      id: 'core-strength',
      name: 'Core Strength',
      category: WorkoutCategory.strength,
      durationMinutes: 20,
      calories: 150,
      difficulty: WorkoutDifficulty.beginner,
      exercises: [
        Exercise(
          id: 'dead-bug',
          name: 'Dead Bug',
          sets: 3,
          repetitions: 10,
          restSeconds: 30,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'bicycle-crunch',
          name: 'Bicycle Crunch',
          sets: 3,
          repetitions: 16,
          restSeconds: 30,
          icon: Icons.autorenew,
        ),
        Exercise(
          id: 'plank-shoulder-tap',
          name: 'Plank Shoulder Tap',
          sets: 3,
          repetitions: 12,
          restSeconds: 30,
          icon: Icons.back_hand_outlined,
        ),
        Exercise(
          id: 'glute-bridge',
          name: 'Glute Bridge',
          sets: 3,
          repetitions: 15,
          restSeconds: 30,
          icon: Icons.airline_seat_recline_normal,
        ),
        Exercise(
          id: 'bird-dog',
          name: 'Bird Dog',
          sets: 3,
          repetitions: 8,
          restSeconds: 30,
          icon: Icons.pets,
        ),
      ],
    ),
    Workout(
      id: 'morning-run-intervals',
      name: 'Morning Run Intervals',
      category: WorkoutCategory.cardio,
      durationMinutes: 30,
      calories: 340,
      difficulty: WorkoutDifficulty.intermediate,
      exercises: [
        Exercise(
          id: 'jumping-jacks',
          name: 'Jumping Jacks',
          sets: 3,
          repetitions: 30,
          restSeconds: 20,
          icon: Icons.directions_run,
        ),
        Exercise(
          id: 'high-knees',
          name: 'High Knees',
          sets: 4,
          repetitions: 20,
          restSeconds: 20,
          icon: Icons.directions_run,
        ),
        Exercise(
          id: 'butt-kicks',
          name: 'Butt Kicks',
          sets: 3,
          repetitions: 20,
          restSeconds: 20,
          icon: Icons.directions_walk,
        ),
        Exercise(
          id: 'mountain-climbers',
          name: 'Mountain Climbers',
          sets: 4,
          repetitions: 16,
          restSeconds: 25,
          icon: Icons.terrain,
        ),
        Exercise(
          id: 'skaters',
          name: 'Skaters',
          sets: 3,
          repetitions: 12,
          restSeconds: 30,
          icon: Icons.swap_horiz,
        ),
      ],
    ),
    Workout(
      id: 'steady-state-cardio',
      name: 'Steady State Cardio',
      category: WorkoutCategory.cardio,
      durationMinutes: 25,
      calories: 220,
      difficulty: WorkoutDifficulty.beginner,
      exercises: [
        Exercise(
          id: 'march-in-place',
          name: 'March in Place',
          sets: 3,
          repetitions: 30,
          restSeconds: 20,
          icon: Icons.directions_walk,
        ),
        Exercise(
          id: 'step-touch',
          name: 'Step Touch',
          sets: 3,
          repetitions: 20,
          restSeconds: 20,
          icon: Icons.swap_horiz,
        ),
        Exercise(
          id: 'standing-knee-lift',
          name: 'Standing Knee Lift',
          sets: 3,
          repetitions: 16,
          restSeconds: 20,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'arm-circles',
          name: 'Arm Circles',
          sets: 2,
          repetitions: 20,
          restSeconds: 15,
          icon: Icons.autorenew,
        ),
      ],
    ),
    Workout(
      id: 'fat-burn-hiit',
      name: 'Fat Burn HIIT',
      category: WorkoutCategory.hiit,
      durationMinutes: 20,
      calories: 280,
      difficulty: WorkoutDifficulty.advanced,
      exercises: [
        Exercise(
          id: 'burpees',
          name: 'Burpees',
          sets: 4,
          repetitions: 10,
          restSeconds: 20,
          icon: Icons.bolt,
        ),
        Exercise(
          id: 'jump-squats',
          name: 'Jump Squats',
          sets: 4,
          repetitions: 12,
          restSeconds: 20,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'push-ups',
          name: 'Push-Ups',
          sets: 4,
          repetitions: 10,
          restSeconds: 20,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'mountain-climbers',
          name: 'Mountain Climbers',
          sets: 4,
          repetitions: 20,
          restSeconds: 15,
          icon: Icons.terrain,
        ),
        Exercise(
          id: 'plank-jacks',
          name: 'Plank Jacks',
          sets: 3,
          repetitions: 12,
          restSeconds: 20,
          icon: Icons.open_in_full,
        ),
        Exercise(
          id: 'skater-hops',
          name: 'Skater Hops',
          sets: 3,
          repetitions: 12,
          restSeconds: 20,
          icon: Icons.swap_horiz,
        ),
      ],
    ),
    Workout(
      id: 'beginner-hiit',
      name: 'Beginner HIIT',
      category: WorkoutCategory.hiit,
      durationMinutes: 15,
      calories: 160,
      difficulty: WorkoutDifficulty.beginner,
      exercises: [
        Exercise(
          id: 'step-jacks',
          name: 'Step Jacks',
          sets: 3,
          repetitions: 16,
          restSeconds: 25,
          icon: Icons.directions_walk,
        ),
        Exercise(
          id: 'squats',
          name: 'Squats',
          sets: 3,
          repetitions: 12,
          restSeconds: 25,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'incline-push-ups',
          name: 'Incline Push-Ups',
          sets: 3,
          repetitions: 8,
          restSeconds: 25,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'standing-knee-drive',
          name: 'Standing Knee Drive',
          sets: 3,
          repetitions: 12,
          restSeconds: 20,
          icon: Icons.directions_run,
        ),
        Exercise(
          id: 'glute-bridge',
          name: 'Glute Bridge',
          sets: 3,
          repetitions: 12,
          restSeconds: 20,
          icon: Icons.airline_seat_recline_normal,
        ),
      ],
    ),
    Workout(
      id: 'full-body-stretch',
      name: 'Full Body Stretch',
      category: WorkoutCategory.flexibility,
      durationMinutes: 15,
      calories: 70,
      difficulty: WorkoutDifficulty.beginner,
      exercises: [
        Exercise(
          id: 'neck-rolls',
          name: 'Neck Rolls',
          sets: 2,
          repetitions: 8,
          restSeconds: 15,
          icon: Icons.self_improvement,
        ),
        Exercise(
          id: 'cat-cow',
          name: 'Cat-Cow',
          sets: 2,
          repetitions: 10,
          restSeconds: 15,
          icon: Icons.pets,
        ),
        Exercise(
          id: 'worlds-greatest-stretch',
          name: "World's Greatest Stretch",
          sets: 2,
          repetitions: 6,
          restSeconds: 20,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'hamstring-reach',
          name: 'Seated Hamstring Reach',
          sets: 2,
          repetitions: 8,
          restSeconds: 20,
          icon: Icons.airline_seat_legroom_extra,
        ),
        Exercise(
          id: 'figure-four',
          name: 'Figure-Four Stretch',
          sets: 2,
          repetitions: 8,
          restSeconds: 20,
          icon: Icons.self_improvement,
        ),
        Exercise(
          id: 'childs-pose',
          name: "Child's Pose Breathing",
          sets: 2,
          repetitions: 8,
          restSeconds: 15,
          icon: Icons.spa,
        ),
      ],
    ),
    Workout(
      id: 'mobility-flow',
      name: 'Mobility Flow',
      category: WorkoutCategory.flexibility,
      durationMinutes: 20,
      calories: 90,
      difficulty: WorkoutDifficulty.intermediate,
      exercises: [
        Exercise(
          id: 'hip-circles',
          name: 'Hip Circles',
          sets: 3,
          repetitions: 8,
          restSeconds: 15,
          icon: Icons.autorenew,
        ),
        Exercise(
          id: 'thoracic-openers',
          name: 'Thoracic Openers',
          sets: 3,
          repetitions: 8,
          restSeconds: 20,
          icon: Icons.open_in_full,
        ),
        Exercise(
          id: 'deep-squat-hold',
          name: 'Deep Squat Hold',
          sets: 3,
          repetitions: 5,
          restSeconds: 20,
          icon: Icons.accessibility_new,
        ),
        Exercise(
          id: 'shoulder-cars',
          name: 'Shoulder CARs',
          sets: 3,
          repetitions: 6,
          restSeconds: 15,
          icon: Icons.autorenew,
        ),
        Exercise(
          id: 'ankle-rocks',
          name: 'Ankle Rocks',
          sets: 3,
          repetitions: 10,
          restSeconds: 15,
          icon: Icons.directions_walk,
        ),
      ],
    ),
    fullBodyStrength,
    Workout(
      id: 'total-body-burn',
      name: 'Total Body Burn',
      category: WorkoutCategory.fullBody,
      durationMinutes: 30,
      calories: 300,
      difficulty: WorkoutDifficulty.intermediate,
      exercises: [
        Exercise(
          id: 'squat-to-press',
          name: 'Squat to Press',
          sets: 3,
          repetitions: 10,
          restSeconds: 40,
          icon: Icons.arrow_upward,
        ),
        Exercise(
          id: 'reverse-lunge',
          name: 'Reverse Lunge',
          sets: 3,
          repetitions: 10,
          restSeconds: 40,
          icon: Icons.directions_walk,
        ),
        Exercise(
          id: 'push-ups',
          name: 'Push-Ups',
          sets: 3,
          repetitions: 10,
          restSeconds: 40,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'bent-over-row',
          name: 'Bent-Over Row',
          sets: 3,
          repetitions: 10,
          restSeconds: 40,
          icon: Icons.swap_vert,
        ),
        Exercise(
          id: 'deadlift',
          name: 'Deadlift',
          sets: 3,
          repetitions: 8,
          restSeconds: 50,
          icon: Icons.fitness_center,
        ),
        Exercise(
          id: 'plank',
          name: 'Plank',
          sets: 3,
          repetitions: 12,
          restSeconds: 30,
          icon: Icons.horizontal_rule,
        ),
      ],
    ),
  ];

  static List<Workout> byCategory(WorkoutCategory? category) {
    if (category == null) return workouts;
    return [
      for (final workout in workouts)
        if (workout.category == category) workout,
    ];
  }
}
